# Minimal configuration with single API key
# This demonstrates the simplest possible configuration

# Server settings
host: "0.0.0.0"
port: 50733
verbose: true

# Single API key (minimal format)
api_keys:
  - key: "your-api-key-here"

# AskSage API settings
asksage_server_base_url: "https://api.asksage.anl.gov/server"
asksage_user_base_url: "https://api.asksage.anl.gov/user"

# Certificate path (required - provide your own certificate file)
cert_path: "/path/to/your/asksage_anl_gov.pem"

# Timeout settings
timeout_seconds: 30.0
